name: vhs
on:
  push:
    paths:
      - vhs/**.tape
  schedule:
    - cron: "0 0 * * 0" # every week

permissions:
  contents: write

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get dependencies
        run: task deps

      - name: Build linux
        run: task linux

      - name: Install vhs deps
        run: |
          sudo apt update
          sudo apt install -y ffmpeg ttyd

      - name: Install vhs
        run: |
          go install github.com/charmbracelet/vhs@latest

      - name: Generate vhs gif
        run: |
          vhs vhs/gobuster_dir.tape -o vhs/gobuster_dir.gif

      - name: commit and push changes
        run: |
          git config user.name "Github"
          git config user.email "<>"
          git add vhs/*.gif
          git commit -m "update vhs gifs" || echo "no changes to commit"
          git push
